// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RonatIa.Games.Infrastructure.Persistence;

#nullable disable

namespace RonatIa.Games.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004233156_AuthSessionVersion")]
    partial class AuthSessionVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RonatIa.Games.Domain.Users.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_label");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<byte[]>("PreviousTokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("previous_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("revoked_reason");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_auth_sessions_expires_at");

                    b.HasIndex("PreviousTokenHash")
                        .HasDatabaseName("ix_auth_sessions_previous_token_hash")
                        .HasFilter("previous_token_hash IS NOT NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_sessions_user_id");

                    b.ToTable("auth_sessions", "app", t =>
                        {
                            t.HasCheckConstraint("ck_auth_sessions_token_hash_len", "octet_length(token_hash) = 32");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Users.Avatar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_avatars");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_avatars_uploaded_by_user_id");

                    b.ToTable("avatars", "app", t =>
                        {
                            t.HasCheckConstraint("ck_avatars_sha256_len", "octet_length(sha256) = 32");

                            t.HasCheckConstraint("ck_avatars_size", "octet_length(data) BETWEEN 1 AND 524288");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarPhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_photo_id");

                    b.Property<string>("AvatarPreset")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("avatar_preset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<byte[]>("PhoneHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("phone_hash");

                    b.Property<string>("PhoneLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("phone_last4")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terms_accepted_at");

                    b.Property<string>("TermsVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("terms_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AvatarPhotoId")
                        .HasDatabaseName("ix_users_avatar_photo_id");

                    b.HasIndex("PhoneHash")
                        .IsUnique()
                        .HasDatabaseName("ux_users_phone_hash");

                    b.ToTable("users", "app", t =>
                        {
                            t.HasCheckConstraint("ck_users_avatar_one_of", "(avatar_preset IS NOT NULL) <> (avatar_photo_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_users_display_name_len", "char_length(display_name) BETWEEN 1 AND 60");

                            t.HasCheckConstraint("ck_users_phone_hash_len", "octet_length(phone_hash) = 32");

                            t.HasCheckConstraint("ck_users_phone_last4", "phone_last4 ~ '^[0-9]{4}$'");

                            t.HasCheckConstraint("ck_users_status", "status IN ('active','suspended','deleted')");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Users.AuthSession", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_users_user_id");
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Users.Avatar", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_avatars_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Users.User", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Users.Avatar", null)
                        .WithMany()
                        .HasForeignKey("AvatarPhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_avatars_avatar_photo_id");
                });
#pragma warning restore 612, 618
        }
    }
}
