// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RonatIa.Games.Infrastructure.Persistence;

#nullable disable

namespace RonatIa.Games.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005004549_Sessions")]
    partial class Sessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RonatIa.Games.Domain.Groups.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character(8)")
                        .HasColumnName("invite_code")
                        .IsFixedLength();

                    b.Property<bool>("InviteEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("invite_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_groups");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasDatabaseName("ux_groups_invite_code");

                    b.ToTable("groups", "app", t =>
                        {
                            t.HasCheckConstraint("ck_groups_invite_code", "invite_code ~ '^[A-HJ-KM-NP-TV-Z2-9]{8}$'");

                            t.HasCheckConstraint("ck_groups_name_len", "char_length(name) BETWEEN 1 AND 80");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Groups.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarPhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_photo_id");

                    b.Property<string>("AvatarPreset")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("avatar_preset");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_group_members");

                    b.HasIndex("AvatarPhotoId")
                        .HasDatabaseName("ix_group_members_avatar_photo_id");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_group_members_group_user")
                        .HasFilter("user_id IS NOT NULL");

                    b.HasIndex(new[] { "GroupId" }, "ix_group_members_group_id")
                        .HasDatabaseName("ix_group_members_group_id");

                    b.HasIndex(new[] { "UserId" }, "ix_group_members_user_active")
                        .HasDatabaseName("ix_group_members_user_active")
                        .HasFilter("status = 'active' AND user_id IS NOT NULL");

                    b.HasIndex(new[] { "GroupId" }, "ux_group_members_one_active_owner")
                        .IsUnique()
                        .HasDatabaseName("ux_group_members_one_active_owner")
                        .HasFilter("role = 'owner' AND status = 'active'");

                    b.ToTable("group_members", "app", t =>
                        {
                            t.HasCheckConstraint("ck_group_members_left_at", "(status = 'active') = (left_at IS NULL)");

                            t.HasCheckConstraint("ck_group_members_owner_has_account", "role <> 'owner' OR user_id IS NOT NULL");

                            t.HasCheckConstraint("ck_group_members_profile_fields", "(user_id IS NOT NULL AND display_name IS NULL AND avatar_preset IS NULL AND avatar_photo_id IS NULL) OR (user_id IS NULL AND display_name IS NOT NULL AND ((avatar_preset IS NOT NULL) <> (avatar_photo_id IS NOT NULL)))");

                            t.HasCheckConstraint("ck_group_members_profile_is_member", "user_id IS NOT NULL OR role = 'member'");

                            t.HasCheckConstraint("ck_group_members_role", "role IN ('member','admin','owner')");

                            t.HasCheckConstraint("ck_group_members_status", "status IN ('active','left','removed')");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Sessions.GameEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ActorPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_player_id");

                    b.Property<Guid?>("ClientActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_action_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Seq")
                        .HasColumnType("integer")
                        .HasColumnName("seq");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_game_events");

                    b.HasIndex("ActorPlayerId")
                        .HasDatabaseName("ix_game_events_actor_player_id");

                    b.HasIndex("SessionId", "ClientActionId")
                        .IsUnique()
                        .HasDatabaseName("ux_game_events_client_action")
                        .HasFilter("client_action_id IS NOT NULL");

                    b.HasIndex("SessionId", "Seq")
                        .IsUnique()
                        .HasDatabaseName("ux_game_events_session_seq");

                    b.ToTable("game_events", "app", t =>
                        {
                            t.HasCheckConstraint("ck_game_events_seq", "seq >= 1");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Sessions.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("game_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<Guid>("HostMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_member_id");

                    b.Property<int>("LastEventSeq")
                        .HasColumnType("integer")
                        .HasColumnName("last_event_seq");

                    b.Property<Guid?>("RematchOfId")
                        .HasColumnType("uuid")
                        .HasColumnName("rematch_of_id");

                    b.Property<int>("RulesVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rules_version");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StateJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("state");

                    b.Property<int?>("StateSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("state_schema_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_game_sessions");

                    b.HasIndex("HostMemberId")
                        .HasDatabaseName("ix_game_sessions_host_member_id");

                    b.HasIndex("RematchOfId")
                        .HasDatabaseName("ix_game_sessions_rematch_of_id");

                    b.HasIndex(new[] { "GroupId" }, "ix_game_sessions_group_active")
                        .HasDatabaseName("ix_game_sessions_group_active")
                        .HasFilter("status IN ('waiting','in_progress')");

                    b.HasIndex(new[] { "GroupId", "CreatedAt" }, "ix_game_sessions_group_created")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_game_sessions_group_created");

                    b.ToTable("game_sessions", "app", t =>
                        {
                            t.HasCheckConstraint("ck_game_sessions_state_pair", "(state IS NULL) = (state_schema_version IS NULL)");

                            t.HasCheckConstraint("ck_game_sessions_state_present", "status NOT IN ('in_progress','finished') OR state IS NOT NULL");

                            t.HasCheckConstraint("ck_game_sessions_status", "status IN ('waiting','in_progress','finished','cancelled')");

                            t.HasCheckConstraint("ck_game_sessions_version", "version >= 0 AND last_event_seq >= 0");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Sessions.ScoreEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EventSeq")
                        .HasColumnType("integer")
                        .HasColumnName("event_seq");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int?>("TeamNo")
                        .HasColumnType("integer")
                        .HasColumnName("team_no");

                    b.HasKey("Id")
                        .HasName("pk_score_entries");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_score_entries_player_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_score_entries_session_id");

                    b.ToTable("score_entries", "app", t =>
                        {
                            t.HasCheckConstraint("ck_score_entries_target", "player_id IS NOT NULL OR team_no IS NOT NULL");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Sessions.SessionPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("Seat")
                        .HasColumnType("integer")
                        .HasColumnName("seat");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TeamNo")
                        .HasColumnType("integer")
                        .HasColumnName("team_no");

                    b.HasKey("Id")
                        .HasName("pk_game_session_players");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_game_session_players_member_id");

                    b.HasIndex("SessionId", "MemberId")
                        .IsUnique()
                        .HasDatabaseName("ux_game_session_players_session_member");

                    b.ToTable("game_session_players", "app", t =>
                        {
                            t.HasCheckConstraint("ck_game_session_players_left_at", "(status = 'joined') = (left_at IS NULL)");

                            t.HasCheckConstraint("ck_game_session_players_status", "status IN ('joined','left','removed')");

                            t.HasCheckConstraint("ck_game_session_players_team", "team_no IS NULL OR team_no BETWEEN 0 AND 15");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Sessions.SessionResult", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("game_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_winner");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<int?>("TeamNo")
                        .HasColumnType("integer")
                        .HasColumnName("team_no");

                    b.HasKey("SessionId", "PlayerId")
                        .HasName("pk_session_results");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_session_results_member_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_session_results_player_id");

                    b.HasIndex("GroupId", "GameId", "MemberId")
                        .HasDatabaseName("ix_session_results_ranking");

                    b.ToTable("session_results", "app", t =>
                        {
                            t.HasCheckConstraint("ck_session_results_rank", "rank >= 1");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Users.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_label");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<byte[]>("PreviousTokenHash")
                        .HasColumnType("bytea")
                        .HasColumnName("previous_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("revoked_reason");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_auth_sessions");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_auth_sessions_expires_at");

                    b.HasIndex("PreviousTokenHash")
                        .HasDatabaseName("ix_auth_sessions_previous_token_hash")
                        .HasFilter("previous_token_hash IS NOT NULL");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_auth_sessions_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_auth_sessions_user_id");

                    b.ToTable("auth_sessions", "app", t =>
                        {
                            t.HasCheckConstraint("ck_auth_sessions_token_hash_len", "octet_length(token_hash) = 32");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Users.Avatar", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<byte[]>("Sha256")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("sha256");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_avatars");

                    b.HasIndex("UploadedByUserId")
                        .HasDatabaseName("ix_avatars_uploaded_by_user_id");

                    b.ToTable("avatars", "app", t =>
                        {
                            t.HasCheckConstraint("ck_avatars_sha256_len", "octet_length(sha256) = 32");

                            t.HasCheckConstraint("ck_avatars_size", "octet_length(data) BETWEEN 1 AND 524288");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvatarPhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("avatar_photo_id");

                    b.Property<string>("AvatarPreset")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("avatar_preset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<byte[]>("PhoneHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("phone_hash");

                    b.Property<string>("PhoneLast4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character(4)")
                        .HasColumnName("phone_last4")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("terms_accepted_at");

                    b.Property<string>("TermsVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("terms_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AvatarPhotoId")
                        .HasDatabaseName("ix_users_avatar_photo_id");

                    b.HasIndex("PhoneHash")
                        .IsUnique()
                        .HasDatabaseName("ux_users_phone_hash");

                    b.ToTable("users", "app", t =>
                        {
                            t.HasCheckConstraint("ck_users_avatar_one_of", "(avatar_preset IS NOT NULL) <> (avatar_photo_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_users_display_name_len", "char_length(display_name) BETWEEN 1 AND 60");

                            t.HasCheckConstraint("ck_users_phone_hash_len", "octet_length(phone_hash) = 32");

                            t.HasCheckConstraint("ck_users_phone_last4", "phone_last4 ~ '^[0-9]{4}$'");

                            t.HasCheckConstraint("ck_users_status", "status IN ('active','suspended','deleted')");
                        });
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Groups.GroupMember", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Users.Avatar", null)
                        .WithMany()
                        .HasForeignKey("AvatarPhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_group_members_avatars_avatar_photo_id");

                    b.HasOne("RonatIa.Games.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_members_groups_group_id");

                    b.HasOne("RonatIa.Games.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_group_members_users_user_id");
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Sessions.GameEventRecord", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Sessions.SessionPlayer", null)
                        .WithMany()
                        .HasForeignKey("ActorPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_game_events_session_players_actor_player_id");

                    b.HasOne("RonatIa.Games.Domain.Sessions.GameSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_events_game_sessions_session_id");
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Sessions.GameSession", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_sessions_groups_group_id");

                    b.HasOne("RonatIa.Games.Domain.Groups.GroupMember", null)
                        .WithMany()
                        .HasForeignKey("HostMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_sessions_group_members_host_member_id");

                    b.HasOne("RonatIa.Games.Domain.Sessions.GameSession", null)
                        .WithMany()
                        .HasForeignKey("RematchOfId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_game_sessions_game_sessions_rematch_of_id");
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Sessions.ScoreEntry", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Sessions.SessionPlayer", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_score_entries_session_players_player_id");

                    b.HasOne("RonatIa.Games.Domain.Sessions.GameSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_entries_game_sessions_session_id");
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Sessions.SessionPlayer", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Groups.GroupMember", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_session_players_group_members_member_id");

                    b.HasOne("RonatIa.Games.Domain.Sessions.GameSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_session_players_game_sessions_session_id");
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Sessions.SessionResult", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Groups.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_results_groups_group_id");

                    b.HasOne("RonatIa.Games.Domain.Groups.GroupMember", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_results_group_members_member_id");

                    b.HasOne("RonatIa.Games.Domain.Sessions.SessionPlayer", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_results_game_session_players_player_id");

                    b.HasOne("RonatIa.Games.Domain.Sessions.GameSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_session_results_game_sessions_session_id");
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Users.AuthSession", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_sessions_users_user_id");
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Users.Avatar", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_avatars_users_uploaded_by_user_id");
                });

            modelBuilder.Entity("RonatIa.Games.Domain.Users.User", b =>
                {
                    b.HasOne("RonatIa.Games.Domain.Users.Avatar", null)
                        .WithMany()
                        .HasForeignKey("AvatarPhotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_users_avatars_avatar_photo_id");
                });
#pragma warning restore 612, 618
        }
    }
}
